version: '3'
services:
    database:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bilemo
        ports:
            - "3306:3306"
